import type { Metadata } from 'next';
import './globals.css';
import { vazirmatn } from './fonts';
//import { vazirmatn } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" className={`${vazirmatn.variable} font-sans`} lang="fa">
      <body>{children}</body>
    </html>
  );
}
